### ISSUE TITLE
网络性能问题

### ISSUE THREAD

**Issue by CMGS** [memoryboxes/dockerfly#1]
多个虚拟网卡绑定到一个混杂模式的物理网卡上，会有网络性能问题

我看了 Readme 里面有写这么一句，能有更详细的说明或者测试咩~~

**Comment by memoryboxes** [comment]
说说目前我在公司里的典型环境:

1台物理机，DELL  R710，32核96G，千兆卡，可以轻松attach 30台以上的container，每台container里面的虚拟网卡是共享千兆卡的，所以无论哪台container都可以跑满1000Mbps，我实际用起来是不用care网络问题，只有那种流量要求非常大的应用，例如视频服务之类的会有问题。

然后内核版本影响很大，如果是unbuntu，kernel >=3.18，如果是redhat系，最好开elrepo 升级到最新内核。

docker的storage推荐用overlay fs。

另外这个东西写来适用于统一测试开发环境的，不适合用在生产系统上面，在container中起root的方法严重违反docker的推荐，很容易某台container改个系统时间，所有container就都挂掉了。

**Comment by memoryboxes** [comment]
然后再公平的说一句，docker用的好不好，其实不是一个工具能解决的事。

这牵扯到  环境定制==>镜像构建 ==>网络构建 一系列的事情，如果想把docker当虚拟机用和vsphere比的话，还是赶紧的上vsphere吧。

**Comment by CMGS** [comment]
T.T 我厂就是视频厂。。。

我们现在是采用 macvlan bridge mode 起的网络层，但网卡是混杂模式，所以比较关心这块。redhat 系我们现在都是自己管理内核了，一水的 3.19-overlay，不过尚未启用，可能新机房那边应该全是 overlay 了。docker 官方取消了对 Centos 6 的支持也是真让人神伤……强逼我们这块集群整体升级，妈蛋 docker 又不能平滑升级来着。。。

我们现在也没用 kubernetes，自己做的调度器，规模也起来点了- - kb 环境太封闭对二次开发还是比较疼的。当然我是觉得无论哪条路，都蛋疼无比，坑太他妈多……

**Comment by memoryboxes** [comment]
我厂是做网络流量监控的， macvlan bridge mode优点是稳定，这方面我觉得还是实践出真知，自己没大规模用过不好瞎猜测。

最近在研究openswitch，发现这个东东的功能还是很强大的，正巧最近会对ovs的性能做一次评估。有什么结论多交流啊。

**Comment by CMGS** [comment]
我们现在是 1.7，不更新偶数版。。因为被 1.4 坑过- -
7.1 现在打算弄几台先测试……目前 macvlan 用在我们的 redis 集群了，基本跑满了网卡，那群上层业务各种大 value 随便塞= =

我们当时选 macvlan 也是因为如果三层的 SDN 要处理的事情太多，对了我们现在也在做 calico 的兼容，以后可能是 calico 和 macvlan 并存。 OVS 的话据说性能不好，unitestack 公司的人讲似乎有 30%~40% 的损失……
